import unittest

from memoria_audiovisual.analysis import (
    NOISE_THEME_LABEL,
    classify_access_regime,
    classify_access_surface,
    infer_video_theme,
)
from memoria_audiovisual.config import EUSCREEN_ABOUT_URL, EUSCREEN_HOME_URL
from memoria_audiovisual.crawler import classify_platform, is_probably_video_link
from memoria_audiovisual.euscreen import (
    _extract_item_id,
    _parse_item_parts,
    _parse_item_text,
    collect_euscreen_institutions,
)


class EUscreenCollectionTests(unittest.TestCase):
    def test_collect_euscreen_institutions_declares_single_aggregator(self):
        institutions = collect_euscreen_institutions()

        self.assertEqual(len(institutions), 1)
        record = institutions[0]
        self.assertEqual(record["institution"], "EUscreen")
        self.assertEqual(record["external_url"], EUSCREEN_HOME_URL)
        self.assertEqual(record["euscreen_detail_url"], EUSCREEN_ABOUT_URL)
        self.assertTrue(record["content_available_in_source"])
        self.assertEqual(record["archive_type"], "European audiovisual aggregator")

    def test_extract_item_id_accepts_collection_and_iframe_urls(self):
        self.assertEqual(
            _extract_item_id("https://www.euscreen.eu/?page_id=388&item_id=EUS_123"),
            "EUS_123",
        )
        self.assertEqual(
            _extract_item_id("https://euscreen.eu/euscreen-collections/item.html?id=EUS_456"),
            "EUS_456",
        )

    def test_parse_item_parts_preserves_provider_and_description_boundaries(self):
        title, provider, description = _parse_item_parts(
            [
                "Opening of the Nuremberg trials",
                "Provider: INA",
                "The first session of the Nuremberg trials.",
            ]
        )

        self.assertEqual(title, "Opening of the Nuremberg trials")
        self.assertEqual(provider, "INA")
        self.assertEqual(description, "The first session of the Nuremberg trials.")

    def test_parse_item_text_falls_back_without_provider_marker(self):
        title, provider, description = _parse_item_text("Louis Armstrong in Prague")

        self.assertEqual(title, "Louis Armstrong in Prague")
        self.assertEqual(provider, "")
        self.assertEqual(description, "")

    def test_euscreen_urls_are_classified_as_audiovisual_surface(self):
        item_url = "https://www.euscreen.eu/?page_id=388&item_id=EUS_123"

        self.assertEqual(classify_platform(item_url), "EUscreen")
        self.assertTrue(is_probably_video_link(item_url, "EUscreen"))
        self.assertEqual(
            classify_access_surface({"platform": "EUscreen", "video_link": item_url}),
            "Agregador audiovisual europeu",
        )
        self.assertEqual(
            classify_access_regime(
                ["Agregador audiovisual europeu"],
                "Evidência pública detectável de audiovisual",
            ),
            "Acesso por agregador audiovisual europeu",
        )

    def test_topic_word_does_not_turn_euscreen_content_into_platform_noise(self):
        theme = infer_video_theme(
            {
                "video_title": "CADIZ: CHIRIGOTAS PERFORM FOR CARNIVAL",
                "video_subject": "TV3 Televisió de Catalunya (TVC)",
                "video_description": (
                    "Performance by one of the chirigota groups that sing satirical songs "
                    "about topics in the news during carnival festivities."
                ),
            }
        )

        self.assertEqual(theme, "Música e performance")

    def test_youtube_generated_music_video_remains_platform_noise(self):
        theme = infer_video_theme(
            {
                "video_title": "Official music video auto-generated by YouTube",
                "video_subject": "",
                "video_description": "",
            }
        )

        self.assertEqual(theme, NOISE_THEME_LABEL)


if __name__ == "__main__":
    unittest.main()
