import unittest

import pandas as pd

from memoria_audiovisual import analysis as analysis_utils
from memoria_audiovisual.dashboard_data import (
    build_dashboard_base_data,
    build_dashboard_overview_data,
)


class DashboardDataTests(unittest.TestCase):
    def setUp(self):
        self.summary_df = pd.DataFrame(
            [
                {
                    "institution": "Arquivo A",
                    "slug": "a",
                    "integrity_status": "integro",
                    "video_links_found_total": "2",
                    "embedded_video_signals_total": 0,
                    "candidate_internal_pages": 0,
                    "website_available": True,
                    "archive_type": "National archives",
                    "country": "Portugal",
                    "continent": "Europe",
                },
                {
                    "institution": "Arquivo B",
                    "slug": "b",
                    "integrity_status": "acessivel",
                    "video_links_found_total": 0,
                    "embedded_video_signals_total": 1,
                    "candidate_internal_pages": 2,
                    "website_available": True,
                    "archive_type": "",
                    "country": "Spain",
                    "continent": "Europe",
                },
                {
                    "institution": "Arquivo C",
                    "slug": "c",
                    "integrity_status": "restrito",
                    "video_links_found_total": 1,
                    "embedded_video_signals_total": 0,
                    "candidate_internal_pages": 0,
                    "website_available": False,
                    "archive_type": "Municipal archives",
                    "country": "Portugal",
                    "continent": "Europe",
                },
                {
                    "institution": "Arquivo D",
                    "slug": " ",
                    "integrity_status": "quebrado",
                    "video_links_found_total": 0,
                    "embedded_video_signals_total": 0,
                    "candidate_internal_pages": 0,
                    "website_available": False,
                    "archive_type": "University and research archives",
                    "country": "",
                    "continent": "",
                },
            ]
        )
        self.links_df = pd.DataFrame(
            [
                {
                    "institution": "Arquivo A",
                    "slug": "a",
                    "platform": "YouTube",
                    "video_link": "https://youtube.com/watch?v=1",
                    "video_title": "Digitisation project overview",
                    "video_subject": "",
                    "video_description": "",
                    "video_published_at": "2025-12-15T00:00:00Z",
                    "country": "Portugal",
                    "continent": "Europe",
                },
                {
                    "institution": "Arquivo C",
                    "slug": "c",
                    "platform": "YouTube",
                    "video_link": "https://youtube.com/watch?v=2",
                    "video_title": "Official music video auto-generated by YouTube",
                    "video_subject": "",
                    "video_description": "",
                    "video_published_at": "",
                    "country": "Portugal",
                    "continent": "Europe",
                },
            ]
        )

    def test_base_data_builds_fallback_frames_and_filters_blank_slugs(self):
        invalid_summary_analysis_df = pd.DataFrame(
            [
                {
                    "slug": "a",
                    "availability_group": "x",
                    "availability_reason": "y",
                    "audiovisual_visibility": "z",
                    "institution_segment": "w",
                }
            ]
        )

        base_data = build_dashboard_base_data(
            catalog_df=None,
            summary_df=self.summary_df,
            links_df=self.links_df,
            internal_df=None,
            summary_analysis_source_df=invalid_summary_analysis_df,
            video_catalog_source_df=None,
        )

        self.assertEqual(len(base_data.summary_analysis_df), len(self.summary_df))
        self.assertEqual(base_data.summary_analysis_df["institution_segment"].nunique(), 3)
        self.assertEqual(base_data.available_slugs, ["a", "b", "c"])
        self.assertEqual(len(base_data.video_catalog_df), len(self.links_df))
        self.assertIn("video_theme", base_data.video_catalog_df.columns)

    def test_overview_data_rebuilds_invalid_precomputed_summaries(self):
        base_data = build_dashboard_base_data(
            catalog_df=None,
            summary_df=self.summary_df,
            links_df=self.links_df,
            internal_df=None,
            summary_analysis_source_df=None,
            video_catalog_source_df=None,
        )

        invalid_theme_counts_df = pd.DataFrame([{"tema": "Tema incorreto", "total": 99}])
        invalid_visibility_counts_df = pd.DataFrame([{"situacao": "Algo", "total": 1}])

        overview_data = build_dashboard_overview_data(
            base_data,
            theme_counts_source_df=invalid_theme_counts_df,
            visibility_counts_source_df=invalid_visibility_counts_df,
        )

        curatorial_catalog = analysis_utils.filter_curatorial_video_catalog(
            base_data.video_catalog_df
        )

        self.assertEqual(overview_data.total_institutions, 4)
        self.assertEqual(overview_data.institutions_with_video, 2)
        self.assertEqual(overview_data.available_with_video_count, 2)
        self.assertEqual(overview_data.unavailable_count, 2)
        self.assertEqual(overview_data.website_count, 2)
        self.assertEqual(
            int(overview_data.theme_counts["total"].sum()),
            len(curatorial_catalog),
        )
        self.assertNotIn(
            analysis_utils.NOISE_THEME_LABEL,
            overview_data.theme_counts["tema"].tolist(),
        )
        self.assertEqual(
            int(overview_data.visibility_counts["total"].sum()),
            len(self.summary_df),
        )
        self.assertFalse(overview_data.theme_country_matrix.empty)


if __name__ == "__main__":
    unittest.main()
