import unittest

import pandas as pd

from memoria_audiovisual.analysis import (
    NOISE_THEME_LABEL,
    build_summary_analysis_df,
    build_video_catalog_df,
    classify_access_regime,
    infer_video_theme,
)
from memoria_audiovisual.config import VIDEO_FILE_EXTENSIONS, VIDEO_HINTS_IN_URL, VIDEO_PLATFORMS
from memoria_audiovisual.crawler import classify_platform, is_probably_video_link


class AudiovisualScopeTests(unittest.TestCase):
    def test_audio_only_platforms_are_not_video_platforms(self):
        self.assertIsNone(classify_platform("https://soundcloud.com/example/archive"))
        self.assertIsNone(classify_platform("https://podcasts.ina.fr/main/pub/emission/demo"))
        self.assertNotIn("soundcloud.com", VIDEO_PLATFORMS)
        self.assertNotIn("podcasts.ina.fr", VIDEO_PLATFORMS)

    def test_audio_only_urls_are_not_video_links(self):
        for url in [
            "https://example.org/audio/episode",
            "https://example.org/sound/archive",
            "https://example.org/files/depoimento.mp3",
            "https://example.org/files/depoimento.wav",
        ]:
            self.assertFalse(is_probably_video_link(url))
        self.assertNotIn("/audio", VIDEO_HINTS_IN_URL)
        self.assertNotIn("/sound", VIDEO_HINTS_IN_URL)
        self.assertNotIn(".mp3", VIDEO_FILE_EXTENSIONS)
        self.assertNotIn(".wav", VIDEO_FILE_EXTENSIONS)

    def test_instagram_photo_posts_are_not_treated_as_video(self):
        self.assertFalse(is_probably_video_link("https://www.instagram.com/p/ABC123/", "Instagram"))
        self.assertTrue(is_probably_video_link("https://www.instagram.com/reel/ABC123/", "Instagram"))

    def test_audio_noise_is_excluded_from_curatorial_theme(self):
        for title in [
            "Official audio auto-generated by YouTube",
            "Podcast 003 - Arquivo histórico",
            "Audio recording available",
            "Audio guide to the collection",
        ]:
            self.assertEqual(infer_video_theme({"video_title": title}), NOISE_THEME_LABEL)

    def test_audio_noise_does_not_enter_curatorial_catalog_or_summary(self):
        links_df = pd.DataFrame(
            [
                {
                    "institution": "Arquivo A",
                    "slug": "a",
                    "platform": "YouTube",
                    "video_link": "https://youtube.com/watch?v=audio",
                    "video_title": "Podcast 003 - Arquivo histórico",
                },
                {
                    "institution": "Arquivo B",
                    "slug": "b",
                    "platform": "YouTube",
                    "video_link": "https://youtube.com/watch?v=video",
                    "video_title": "Archive tour",
                },
            ]
        )
        summary_df = pd.DataFrame(
            [
                {"slug": "a", "integrity_status": "integro", "video_links_found_total": 1, "embedded_video_signals_total": 0, "candidate_internal_pages": 0},
                {"slug": "b", "integrity_status": "integro", "video_links_found_total": 1, "embedded_video_signals_total": 0, "candidate_internal_pages": 0},
            ]
        )

        catalog_df = build_video_catalog_df(links_df)
        summary_analysis_df = build_summary_analysis_df(summary_df, catalog_df).set_index("slug")

        self.assertEqual(len(catalog_df), 1)
        self.assertEqual(catalog_df.iloc[0]["slug"], "b")
        self.assertEqual(summary_analysis_df.loc["a", "institution_segment"], "Disponíveis sem vídeos")
        self.assertEqual(summary_analysis_df.loc["b", "institution_segment"], "Disponíveis com vídeos")

    def test_podcast_modality_is_not_a_valid_access_regime(self):
        regime = classify_access_regime(
            ["Podcast público"],
            "Evidência pública detectável de audiovisual",
        )

        self.assertNotIn("podcast", regime.lower())


if __name__ == "__main__":
    unittest.main()
