from pathlib import Path
import re
import unicodedata
from urllib.parse import urlparse

import pandas as pd
import streamlit as st
import streamlit.components.v1 as components


BASE_DIR = Path(__file__).resolve().parents[1]
OUTPUT_DIR = BASE_DIR / "data" / "output"

st.set_page_config(
    page_title="Memória Audiovisual em Rede",
    layout="wide",
)


def load_csv(filename):
    path = OUTPUT_DIR / filename
    if not path.exists():
        return None
    return pd.read_csv(path)


def normalize_text(value, fallback="-"):
    if pd.isna(value):
        return fallback
    text = str(value).strip()
    return text if text else fallback


def normalize_optional_text(value):
    if pd.isna(value):
        return ""
    return str(value).strip()


def format_video_date(value):
    text = normalize_optional_text(value)
    if not text:
        return ""
    parsed = pd.to_datetime(text, errors="coerce", utc=True)
    if pd.isna(parsed):
        return text
    return parsed.strftime("%Y-%m-%d")


def normalize_for_matching(value):
    text = normalize_optional_text(value).lower()
    text = unicodedata.normalize("NFKD", text)
    text = "".join(char for char in text if not unicodedata.combining(char))
    return text


def text_has_any_keyword(text, keywords):
    return any(keyword in text for keyword in keywords)


def infer_video_theme(row):
    combined_text = " ".join(
        [
            normalize_optional_text(row.get("video_title")),
            normalize_optional_text(row.get("video_subject")),
            normalize_optional_text(row.get("video_description")),
        ]
    )
    normalized = normalize_for_matching(combined_text)

    noise_patterns = [
        "provided to youtube",
        "auto-generated by youtube",
        "youtube",
        "topic",
        "vevo",
        "official audio",
        "official music video",
        "licensed to youtube",
    ]
    if text_has_any_keyword(normalized, noise_patterns):
        return "Ruído de plataforma ou incorporação externa"

    theme_rules = [
        (
            "Apresentação institucional",
            [
                "imagefilm",
                "moodfilm",
                "promo",
                "promotional",
                "introduction",
                "introduct",
                "archive tour",
                "about the archive",
                "about us",
                "presentation",
                "presentatie",
                "presentation du service",
                "institutional",
                "a propos",
                "qui sommes",
                "uber uns",
                "welcome to",
                "mission",
                "who we are",
                "our archive",
                "our archives",
            ],
        ),
        (
            "Visita e descoberta do arquivo",
            [
                "discover",
                "discover our",
                "visit us",
                "visite",
                "tour",
                "guided tour",
                "virtual tour",
                "walkthrough",
                "behind the scenes",
                "open day",
                "journees du patrimoine",
                "portes ouvertes",
                "open house",
            ],
        ),
        (
            "Divulgação de serviços e projetos",
            [
                "campaign",
                "launch",
                "announcement",
                "annonce",
                "highlights",
                "promotion",
                "project",
                "initiative",
                "service",
                "services",
                "program",
                "programme",
                "platform",
                "tool",
                "resource",
                "new website",
                "new portal",
            ],
        ),
        (
            "Comunicação institucional",
            [
                "spot",
                "teaser",
                "trailer",
                "promo clip",
                "institutional communication",
                "message from",
                "greetings",
                "statement",
                "address by",
                "news",
                "newsletter",
            ],
        ),
        (
            "Digitalização e acesso",
            [
                "digit",
                "digitalis",
                "digitaliz",
                "online",
                "search",
                "zoeken",
                "catalog",
                "catalogue",
                "http://search.",
                "zoek",
                "database",
                "portal",
                "scan",
                "metadata",
                "open data",
                "access",
                "consultation",
                "discovery",
                "finder",
            ],
        ),
        (
            "Coleções e serviços",
            [
                "collection",
                "collections",
                "collectie",
                "sammlung",
                "fonds",
                "archive holdings",
                "services",
                "reading room",
                "record office",
                "kadaster",
                "inventar",
                "inventaire",
                "manuscript",
                "manuscripts",
                "photograph",
                "photographs",
                "special collections",
                "library",
                "bibliotheek",
                "bibliotheque",
                "map collection",
                "photo archive",
                "film archive",
                "sound archive",
            ],
        ),
        (
            "Preservação e conservação",
            [
                "preservation",
                "conservation",
                "restoration",
                "restaur",
                "preserv",
                "conserv",
                "film preservation",
                "storage",
                "repair",
                "climate",
                "vault",
            ],
        ),
        (
            "Formação e mediação",
            [
                "tutorial",
                "instructievideo",
                "instruction",
                "how to",
                "workshop",
                "academy",
                "teaching",
                "learning",
                "education",
                "didactic",
                "mediation",
                "lesson",
                "course",
                "seminar",
                "classroom",
                "pedagog",
            ],
        ),
        (
            "Exposições e eventos",
            [
                "exhibition",
                "expo",
                "festival",
                "event",
                "conference",
                "symposium",
                "vernissage",
                "opening",
                "programma",
                "programme",
                "program",
                "journee",
                "tagung",
                "celebration",
                "anniversary",
            ],
        ),
        (
            "Música e performance",
            [
                "music",
                "musica",
                "muziek",
                "soundpainting",
                "concert",
                "performance",
                "orchestra",
                "choir",
                "opera",
                "live",
                "theatre",
                "theater",
                "dance",
                "stage",
            ],
        ),
        (
            "Memória, narrativa e testemunho",
            [
                "oral history",
                "testimony",
                "testimonial",
                "memoir",
                "memories",
                "souvenir",
                "witness",
                "interview",
                "story",
                "narrative",
                "remembrance",
                "legacy",
                "biography",
                "life story",
            ],
        ),
        (
            "História e pesquisa",
            [
                "history",
                "histor",
                "research",
                "study",
                "patrimony",
                "heritage",
                "erfgoed",
                "past",
                "war",
                "archive research",
                "historical",
                "geschichte",
                "histoire",
                "historie",
                "scholar",
                "academic",
                "documentary",
                "heritage studies",
            ],
        ),
        (
            "Acervo e patrimônio",
            [
                "archive",
                "archiv",
                "archives",
                "archivo",
                "arxiu",
                "heritage",
                "patrimoine",
                "patrimonio",
                "erfgoed",
                "memory",
                "memoire",
                "memoria",
                "municipal",
                "state archive",
                "city archive",
                "national archive",
                "regional archive",
                "historical archive",
                "library and archives",
                "cultural heritage",
                "documentary heritage",
                "archive collection",
            ],
        ),
        (
            "Memória institucional",
            [
                "memory of the institution",
                "institutional memory",
                "history of the archive",
                "archive history",
                "history of the institution",
                "our history",
                "legacy of",
                "historique",
                "geschichte des archivs",
            ],
        ),
    ]

    for theme_name, keywords in theme_rules:
        if text_has_any_keyword(normalized, keywords):
            return theme_name

    if re.search(r"\b(memory|memoria|memoire|legacy|historique)\b", normalized):
        return "Memória institucional"
    if re.search(r"\b(archive|archiv|archivo|arxiu|archives|heritage|library|patrimoine|patrimonio|erfgoed)\b", normalized):
        return "Acervo e patrimônio"
    if re.search(r"\b(visit|tour|discover|open day|portes ouvertes|open house)\b", normalized):
        return "Visita e descoberta do arquivo"
    if re.search(r"\b(project|service|platform|portal|resource|tool|initiative|launch|announcement)\b", normalized):
        return "Divulgação de serviços e projetos"
    if normalized.strip():
        return "Comunicação institucional"
    return "Tema não identificado"


def render_integrity_badge(value):
    colors = {
        "integro": "#2f7d32",
        "acessivel": "#4c8bf5",
        "suspeito": "#8e44ad",
        "restrito": "#d97706",
        "quebrado": "#c62828",
        "instavel": "#6b7280",
        "sem_site": "#475569",
    }
    color = colors.get(str(value), "#6b7280")
    st.markdown(
        f"""
        <div style="display:inline-block;padding:0.3rem 0.7rem;border-radius:999px;
        background:{color};color:white;font-weight:600;font-size:0.9rem;">
        {value}
        </div>
        """,
        unsafe_allow_html=True,
    )


def get_vimeo_embed_url(url):
    parsed = urlparse(url)
    if parsed.netloc.lower().startswith("player.vimeo.com") and "/video/" in parsed.path:
        return url
    path_parts = [part for part in parsed.path.split("/") if part]
    if parsed.netloc.lower().endswith("vimeo.com") and path_parts and path_parts[-1].isdigit():
        return f"https://player.vimeo.com/video/{path_parts[-1]}"
    return None


def build_detected_sites_df(summary_df, links_df):
    ranked = summary_df.loc[summary_df["video_links_found_total"] > 0].copy()

    if ranked.empty:
        return ranked

    platforms_df = pd.DataFrame(columns=["slug", "platforms_detectadas"])
    if not links_df.empty:
        platforms_df = (
            links_df.groupby("slug")["platform"]
            .apply(lambda values: ", ".join(sorted(pd.unique(values))))
            .reset_index(name="platforms_detectadas")
        )

    ranked = ranked.merge(platforms_df, on="slug", how="left")
    ranked["platforms_detectadas"] = ranked["platforms_detectadas"].fillna("")

    return ranked.sort_values(
        [
            "video_links_found_total",
            "embedded_video_signals_total",
            "integrity_status",
            "institution",
        ],
        ascending=[False, False, True, True],
    )


def build_geography_summaries(df):
    if df.empty:
        return (
            pd.DataFrame(columns=["continent", "instituicoes"]),
            pd.DataFrame(columns=["country", "instituicoes"]),
        )

    continent_counts = (
        df["continent"]
        .fillna("Não classificado")
        .replace("", "Não classificado")
        .value_counts()
        .rename_axis("continent")
        .reset_index(name="instituicoes")
    )
    country_counts = (
        df["country"]
        .fillna("Não classificado")
        .replace("", "Não classificado")
        .value_counts()
        .rename_axis("country")
        .reset_index(name="instituicoes")
    )
    return continent_counts, country_counts


def build_platform_summary(links_df):
    if links_df.empty:
        return pd.DataFrame(columns=["platform", "total"])
    return (
        links_df["platform"]
        .value_counts()
        .rename_axis("platform")
        .reset_index(name="total")
    )


def classify_availability_group(integrity_status):
    status = normalize_optional_text(integrity_status)
    if status in {"integro", "acessivel"}:
        return "Disponível"
    return "Indisponível"


def classify_availability_reason(row):
    status = normalize_optional_text(row.get("integrity_status"))
    if status == "integro":
        return "Disponível: íntegro"
    if status == "acessivel":
        return "Disponível: acessível"
    if status == "suspeito":
        return "Indisponível: quebrado (página suspeita)"
    if status == "restrito":
        return "Indisponível: restrito"
    if status == "quebrado":
        return "Indisponível: quebrado (erro explícito)"
    if status == "instavel":
        error_text = normalize_optional_text(row.get("error")).lower()
        if "timeout" in error_text:
            return "Indisponível: instável (timeout ou falha de carregamento)"
        if error_text:
            return "Indisponível: instável (erro de navegação)"
        return "Indisponível: instável"
    if status == "sem_site":
        return "Indisponível: sem site"
    return "Indisponível: outro"


def build_availability_reference():
    return pd.DataFrame(
        [
            {
                "categoria": "Disponível",
                "subcategoria": "íntegro",
                "descricao": "O site respondeu de forma confiável e a página final parece válida.",
            },
            {
                "categoria": "Disponível",
                "subcategoria": "acessível",
                "descricao": "O site respondeu, mas sem sinal forte de integridade plena.",
            },
            {
                "categoria": "Indisponível",
                "subcategoria": "quebrado (erro explícito)",
                "descricao": "O site retornou erro claro, como 404, 410 ou 5xx.",
            },
            {
                "categoria": "Indisponível",
                "subcategoria": "quebrado (página suspeita)",
                "descricao": "O site respondeu, mas abriu página genérica, suspensa, placeholder ou erro disfarçado.",
            },
            {
                "categoria": "Indisponível",
                "subcategoria": "restrito",
                "descricao": "O acesso exige permissão, autenticação ou foi bloqueado.",
            },
            {
                "categoria": "Indisponível",
                "subcategoria": "instável (timeout ou falha de carregamento)",
                "descricao": "A página não carregou de forma confiável dentro do tempo esperado ou falhou durante a navegação.",
            },
            {
                "categoria": "Indisponível",
                "subcategoria": "instável (erro de navegação)",
                "descricao": "A navegação falhou sem código HTTP explícito, por erro de navegador, sessão ou carregamento.",
            },
            {
                "categoria": "Indisponível",
                "subcategoria": "sem site",
                "descricao": "A ficha no APE não informa webpage externa.",
            },
        ]
    )


def build_availability_summary(summary_df):
    enriched = summary_df.copy()
    enriched["availability_group"] = enriched["integrity_status"].apply(classify_availability_group)
    enriched["availability_reason"] = enriched.apply(classify_availability_reason, axis=1)

    group_counts = (
        enriched["availability_group"]
        .value_counts()
        .rename_axis("categoria")
        .reset_index(name="total")
    )
    reason_counts = (
        enriched["availability_reason"]
        .value_counts()
        .rename_axis("subcategoria")
        .reset_index(name="total")
    )
    return enriched, group_counts, reason_counts


def build_archive_type_summary(summary_df):
    if summary_df.empty or "archive_type" not in summary_df.columns:
        return pd.DataFrame(columns=["tipo_institucional", "total"])
    enriched = summary_df.copy()
    enriched["archive_type_display"] = (
        enriched["archive_type"]
        .fillna("Não informado no APE")
        .astype(str)
        .str.strip()
        .replace("", "Não informado no APE")
    )
    return (
        enriched["archive_type_display"]
        .value_counts()
        .rename_axis("tipo_institucional")
        .reset_index(name="total")
    )


def classify_audiovisual_visibility(row):
    status = normalize_optional_text(row.get("integrity_status"))
    video_links = pd.to_numeric(row.get("video_links_found_total"), errors="coerce")
    embedded_signals = pd.to_numeric(row.get("embedded_video_signals_total"), errors="coerce")
    internal_pages = pd.to_numeric(row.get("candidate_internal_pages"), errors="coerce")

    video_links = 0 if pd.isna(video_links) else int(video_links)
    embedded_signals = 0 if pd.isna(embedded_signals) else int(embedded_signals)
    internal_pages = 0 if pd.isna(internal_pages) else int(internal_pages)

    if video_links > 0:
        return "Evidência pública detectável de audiovisual"
    if embedded_signals > 0:
        return "Evidência pública indireta de audiovisual"
    if status in {"integro", "acessivel"} and internal_pages > 0:
        return "Potencial audiovisual em navegação interna"
    if status in {"integro", "acessivel"}:
        return "Sem evidência pública detectável de audiovisual"
    return "Site indisponível para verificação"


def build_visibility_summary(summary_df):
    enriched = summary_df.copy()
    enriched["audiovisual_visibility"] = enriched.apply(classify_audiovisual_visibility, axis=1)
    visibility_counts = (
        enriched["audiovisual_visibility"]
        .value_counts()
        .rename_axis("situacao")
        .reset_index(name="total")
    )
    return enriched, visibility_counts


def build_institution_segments(summary_df):
    segmented = summary_df.copy()
    segmented["availability_group"] = segmented["integrity_status"].apply(classify_availability_group)
    segmented["video_links_found_total"] = pd.to_numeric(
        segmented["video_links_found_total"], errors="coerce"
    ).fillna(0)
    segmented["institution_segment"] = "Indisponíveis"
    segmented.loc[
        segmented["video_links_found_total"] > 0,
        "institution_segment",
    ] = "Disponíveis com vídeos"
    segmented.loc[
        (segmented["availability_group"] == "Disponível")
        & (segmented["video_links_found_total"] <= 0),
        "institution_segment",
    ] = "Disponíveis sem vídeos"
    return segmented


def build_video_catalog_df(links_df):
    if links_df.empty:
        return pd.DataFrame(
            columns=[
                "institution",
                "platform",
                "video_title",
                "video_subject",
                "video_published_at",
                "country",
                "continent",
                "video_link",
            ]
        )

    catalog = links_df.copy()
    for column in ["video_title", "video_subject", "video_description", "video_published_at"]:
        if column not in catalog.columns:
            catalog[column] = ""

    catalog["video_title"] = catalog["video_title"].fillna("").astype(str).str.strip()
    catalog["video_subject"] = catalog["video_subject"].fillna("").astype(str).str.strip()
    catalog["video_published_at"] = catalog["video_published_at"].fillna("").astype(str).str.strip()
    catalog["video_title_display"] = catalog["video_title"]
    catalog.loc[catalog["video_title_display"] == "", "video_title_display"] = (
        catalog.loc[catalog["video_title_display"] == "", "video_subject"]
    )
    catalog.loc[catalog["video_title_display"] == "", "video_title_display"] = (
        catalog.loc[catalog["video_title_display"] == "", "video_link"]
    )
    catalog["video_date_display"] = catalog["video_published_at"].apply(format_video_date)
    catalog["video_theme"] = catalog.apply(infer_video_theme, axis=1)

    return catalog.sort_values(
        ["institution", "platform", "video_date_display", "video_title_display"],
        ascending=[True, True, False, True],
    )


def build_theme_summary(video_catalog_df):
    if video_catalog_df.empty or "video_theme" not in video_catalog_df.columns:
        return pd.DataFrame(columns=["tema", "total"])
    filtered_catalog = video_catalog_df.loc[
        video_catalog_df["video_theme"] != "Ruído de plataforma ou incorporação externa"
    ].copy()
    if filtered_catalog.empty:
        return pd.DataFrame(columns=["tema", "total"])
    return (
        filtered_catalog["video_theme"]
        .value_counts()
        .rename_axis("tema")
        .reset_index(name="total")
    )


def build_theme_country_summary(video_catalog_df, top_n=10):
    if video_catalog_df.empty or "video_theme" not in video_catalog_df.columns:
        return pd.DataFrame(columns=["tema", "pais", "total"])
    filtered_catalog = video_catalog_df.loc[
        video_catalog_df["video_theme"] != "Ruído de plataforma ou incorporação externa"
    ].copy()
    if filtered_catalog.empty:
        return pd.DataFrame(columns=["tema", "pais", "total"])
    summary = (
        filtered_catalog.assign(
            country=filtered_catalog["country"]
            .fillna("Nao classificado")
            .replace("", "Nao classificado")
        )
        .groupby(["video_theme", "country"])
        .size()
        .reset_index(name="total")
        .sort_values(["total", "video_theme", "country"], ascending=[False, True, True])
        .head(top_n)
        .rename(columns={"video_theme": "tema", "country": "pais"})
    )
    return summary


def build_theme_country_matrix(video_catalog_df, top_countries=10, top_themes=8):
    if video_catalog_df.empty or "video_theme" not in video_catalog_df.columns:
        return pd.DataFrame()
    filtered_catalog = video_catalog_df.loc[
        video_catalog_df["video_theme"] != "Ruído de plataforma ou incorporação externa"
    ].copy()
    if filtered_catalog.empty:
        return pd.DataFrame()

    filtered_catalog["country_display"] = (
        filtered_catalog["country"]
        .fillna("Não classificado")
        .replace("", "Não classificado")
    )
    top_country_values = (
        filtered_catalog["country_display"].value_counts().head(top_countries).index.tolist()
    )
    top_theme_values = (
        filtered_catalog["video_theme"].value_counts().head(top_themes).index.tolist()
    )

    matrix_source = filtered_catalog[
        filtered_catalog["country_display"].isin(top_country_values)
        & filtered_catalog["video_theme"].isin(top_theme_values)
    ].copy()
    if matrix_source.empty:
        return pd.DataFrame()

    matrix = pd.crosstab(
        matrix_source["country_display"],
        matrix_source["video_theme"],
    )
    matrix = matrix.reindex(index=top_country_values, columns=top_theme_values, fill_value=0)
    matrix.index.name = "país"
    return matrix.reset_index()


def build_theme_platform_summary(video_catalog_df, top_n=10):
    if video_catalog_df.empty or "video_theme" not in video_catalog_df.columns:
        return pd.DataFrame(columns=["tema", "plataforma", "total"])
    filtered_catalog = video_catalog_df.loc[
        video_catalog_df["video_theme"] != "Ruído de plataforma ou incorporação externa"
    ].copy()
    if filtered_catalog.empty:
        return pd.DataFrame(columns=["tema", "plataforma", "total"])
    summary = (
        filtered_catalog.groupby(["video_theme", "platform"])
        .size()
        .reset_index(name="total")
        .sort_values(["total", "video_theme", "platform"], ascending=[False, True, True])
        .head(top_n)
        .rename(columns={"video_theme": "tema", "platform": "plataforma"})
    )
    return summary


def build_theme_archive_type_summary(video_catalog_df, summary_df, top_n=12):
    if (
        video_catalog_df.empty
        or "video_theme" not in video_catalog_df.columns
        or summary_df.empty
        or "slug" not in summary_df.columns
    ):
        return pd.DataFrame(columns=["tema", "tipo_institucional", "total"])

    filtered_catalog = video_catalog_df.loc[
        video_catalog_df["video_theme"] != "Ruído de plataforma ou incorporação externa"
    ].copy()
    if filtered_catalog.empty:
        return pd.DataFrame(columns=["tema", "tipo_institucional", "total"])

    archive_lookup = summary_df[["slug", "archive_type"]].copy()
    archive_lookup["archive_type_display"] = (
        archive_lookup["archive_type"]
        .fillna("Não informado no APE")
        .astype(str)
        .str.strip()
        .replace("", "Não informado no APE")
    )

    merged = filtered_catalog.merge(
        archive_lookup[["slug", "archive_type_display"]],
        on="slug",
        how="left",
    )
    summary = (
        merged.groupby(["video_theme", "archive_type_display"])
        .size()
        .reset_index(name="total")
        .sort_values(
            ["total", "video_theme", "archive_type_display"],
            ascending=[False, True, True],
        )
        .head(top_n)
        .rename(
            columns={
                "video_theme": "tema",
                "archive_type_display": "tipo_institucional",
            }
        )
    )
    return summary


def build_theme_archive_type_matrix(video_catalog_df, summary_df, top_archive_types=8, top_themes=8):
    if (
        video_catalog_df.empty
        or "video_theme" not in video_catalog_df.columns
        or summary_df.empty
        or "slug" not in summary_df.columns
    ):
        return pd.DataFrame()

    filtered_catalog = video_catalog_df.loc[
        video_catalog_df["video_theme"] != "Ruído de plataforma ou incorporação externa"
    ].copy()
    if filtered_catalog.empty:
        return pd.DataFrame()

    archive_lookup = summary_df[["slug", "archive_type"]].copy()
    archive_lookup["archive_type_display"] = (
        archive_lookup["archive_type"]
        .fillna("Não informado no APE")
        .astype(str)
        .str.strip()
        .replace("", "Não informado no APE")
    )

    merged = filtered_catalog.merge(archive_lookup[["slug", "archive_type_display"]], on="slug", how="left")
    top_archive_type_values = (
        merged["archive_type_display"].value_counts().head(top_archive_types).index.tolist()
    )
    top_theme_values = (
        merged["video_theme"].value_counts().head(top_themes).index.tolist()
    )

    matrix_source = merged[
        merged["archive_type_display"].isin(top_archive_type_values)
        & merged["video_theme"].isin(top_theme_values)
    ].copy()
    if matrix_source.empty:
        return pd.DataFrame()

    matrix = pd.crosstab(
        matrix_source["archive_type_display"],
        matrix_source["video_theme"],
    )
    matrix = matrix.reindex(index=top_archive_type_values, columns=top_theme_values, fill_value=0)
    matrix.index.name = "tipo_institucional"
    return matrix.reset_index()


def build_visibility_archive_type_summary(summary_df, top_n=12):
    if summary_df.empty:
        return pd.DataFrame(columns=["visibilidade", "tipo_institucional", "total"])

    enriched = summary_df.copy()
    enriched["audiovisual_visibility"] = enriched.apply(classify_audiovisual_visibility, axis=1)
    enriched["archive_type_display"] = (
        enriched["archive_type"]
        .fillna("Não informado no APE")
        .astype(str)
        .str.strip()
        .replace("", "Não informado no APE")
    )

    summary = (
        enriched.groupby(["audiovisual_visibility", "archive_type_display"])
        .size()
        .reset_index(name="total")
        .sort_values(["total", "audiovisual_visibility", "archive_type_display"], ascending=[False, True, True])
        .head(top_n)
        .rename(
            columns={
                "audiovisual_visibility": "visibilidade",
                "archive_type_display": "tipo_institucional",
            }
        )
    )
    return summary


def build_visibility_archive_type_matrix(summary_df, top_archive_types=8):
    if summary_df.empty:
        return pd.DataFrame()

    enriched = summary_df.copy()
    enriched["audiovisual_visibility"] = enriched.apply(classify_audiovisual_visibility, axis=1)
    enriched["archive_type_display"] = (
        enriched["archive_type"]
        .fillna("Não informado no APE")
        .astype(str)
        .str.strip()
        .replace("", "Não informado no APE")
    )

    top_archive_type_values = (
        enriched["archive_type_display"].value_counts().head(top_archive_types).index.tolist()
    )
    visibility_order = [
        "Evidência pública detectável de audiovisual",
        "Evidência pública indireta de audiovisual",
        "Potencial audiovisual em navegação interna",
        "Sem evidência pública detectável de audiovisual",
        "Site indisponível para verificação",
    ]

    matrix_source = enriched[
        enriched["archive_type_display"].isin(top_archive_type_values)
    ].copy()
    if matrix_source.empty:
        return pd.DataFrame()

    matrix = pd.crosstab(
        matrix_source["archive_type_display"],
        matrix_source["audiovisual_visibility"],
    )
    available_visibility_columns = [col for col in visibility_order if col in matrix.columns]
    matrix = matrix.reindex(index=top_archive_type_values, columns=available_visibility_columns, fill_value=0)
    matrix.index.name = "tipo_institucional"
    return matrix.reset_index()


def prepare_matrix_display(matrix_df):
    if matrix_df.empty:
        return matrix_df

    display_df = matrix_df.copy()
    label_col = display_df.columns[0]
    numeric_cols = [col for col in display_df.columns[1:] if pd.api.types.is_numeric_dtype(display_df[col])]
    if not numeric_cols:
        return display_df

    display_df["Total"] = display_df[numeric_cols].sum(axis=1)
    total_row = {label_col: "Total"}
    for column in numeric_cols:
        total_row[column] = display_df[column].sum()
    total_row["Total"] = display_df["Total"].sum()

    return pd.concat([display_df, pd.DataFrame([total_row])], ignore_index=True)


def style_matrix_display(matrix_df):
    if matrix_df.empty:
        return matrix_df
    numeric_cols = matrix_df.select_dtypes(include="number").columns.tolist()
    styler = matrix_df.style
    if numeric_cols:
        styler = styler.background_gradient(subset=numeric_cols, cmap="Blues")
    return styler


catalog_df = load_csv("ape_instituicoes.csv")
summary_df = load_csv("ape_resumo_instituicoes.csv")
links_df = load_csv("ape_links_video.csv")
internal_df = load_csv("ape_paginas_internas.csv")

st.title("Plataforma aberta de curadoria e acesso à memória audiovisual em rede")
st.caption(
    "Versão focada no Archives Portal Europe (APE), a partir da lista oficial de instituições "
    "com conteúdo publicado e da verificação dos sites externos de cada instituição."
)

if summary_df is None:
    st.warning("Nenhum relatório do APE foi gerado ainda. Execute `python scripts/run_pipeline.py` primeiro.")
    st.stop()

catalog_df = catalog_df if catalog_df is not None else pd.DataFrame()
links_df = links_df if links_df is not None else pd.DataFrame(columns=["institution", "slug", "platform", "video_link"])
internal_df = internal_df if internal_df is not None else pd.DataFrame()

for frame in [catalog_df, summary_df, links_df, internal_df]:
    if "archive_type" not in frame.columns:
        frame["archive_type"] = ""
    if "ape_detail_url" not in frame.columns:
        frame["ape_detail_url"] = ""
    if "website_available" not in frame.columns:
        frame["website_available"] = False
    if "country" not in frame.columns:
        frame["country"] = ""
    if "continent" not in frame.columns:
        frame["continent"] = "Não classificado"
    if "warning" not in frame.columns:
        frame["warning"] = ""
    if "video_title" not in frame.columns:
        frame["video_title"] = ""
    if "video_subject" not in frame.columns:
        frame["video_subject"] = ""
    if "video_description" not in frame.columns:
        frame["video_description"] = ""
    if "video_published_at" not in frame.columns:
        frame["video_published_at"] = ""

if summary_df.empty:
    st.warning(
        "O relatório do APE foi gerado, mas veio sem instituições. Revise a execução do "
        "`scripts/run_pipeline.py` e confira o arquivo `data/output/ape_relatorio.txt`."
    )
    st.stop()

query_params = st.query_params
requested_slug = query_params.get("instituicao")
available_slugs = summary_df["slug"].dropna().tolist()
if not available_slugs:
    st.warning(
        "O relatório do APE não trouxe slugs de instituição. Revise o CSV "
        "`data/output/ape_resumo_instituicoes.csv` antes de abrir a interface."
    )
    st.stop()

available_slugs = [str(slug) for slug in available_slugs if str(slug).strip()]
segmented_summary_df = build_institution_segments(summary_df)


def format_institution_label(slug):
    label_series = summary_df.loc[summary_df["slug"].astype(str) == str(slug), "institution"]
    if label_series.empty:
        return str(slug)
    label = normalize_optional_text(label_series.iloc[0])
    return label or str(slug)


def format_segment_label(segment_name):
    total = int((segmented_summary_df["institution_segment"] == segment_name).sum())
    return f"{segment_name} ({total})"

sidebar_mode = st.sidebar.radio(
    "Modo",
    options=["Visão geral", "Página da instituição"],
)

st.sidebar.subheader("Instituição")
st.sidebar.caption(
    "A lista separa instituições com vídeos clicáveis, instituições disponíveis sem vídeos "
    "e instituições indisponíveis."
)
segment_options = [
    "Disponíveis com vídeos",
    "Disponíveis sem vídeos",
    "Indisponíveis",
]

default_segment = "Disponíveis com vídeos"
if requested_slug in available_slugs:
    requested_segment_series = segmented_summary_df.loc[
        segmented_summary_df["slug"].astype(str) == str(requested_slug),
        "institution_segment",
    ]
    if not requested_segment_series.empty:
        default_segment = requested_segment_series.iloc[0]

selected_segment = st.sidebar.radio(
    "Recorte da lista",
    options=segment_options,
    index=segment_options.index(default_segment),
    format_func=format_segment_label,
)

filtered_summary_df = segmented_summary_df.loc[
    segmented_summary_df["institution_segment"] == selected_segment
].sort_values("institution")
filtered_slugs = filtered_summary_df["slug"].astype(str).tolist()

if not filtered_slugs:
    st.sidebar.info("Nenhuma instituição se enquadra neste recorte.")
    filtered_slugs = available_slugs

default_slug = requested_slug if requested_slug in filtered_slugs else filtered_slugs[0]

selected_slug = st.sidebar.selectbox(
    "Selecione uma instituição do APE",
    options=filtered_slugs,
    index=filtered_slugs.index(default_slug),
    format_func=format_institution_label,
)
query_params["instituicao"] = selected_slug

sidebar_video_catalog_df = build_video_catalog_df(links_df)
sidebar_theme_options = []
if not sidebar_video_catalog_df.empty:
    sidebar_theme_options = sorted(
        [
            theme
            for theme in sidebar_video_catalog_df["video_theme"].dropna().unique().tolist()
            if theme != "Ruído de plataforma ou incorporação externa"
        ]
    )

st.sidebar.subheader("Tema")
selected_sidebar_theme = st.sidebar.selectbox(
    "Selecione o tema",
    options=["Todos os temas"] + sidebar_theme_options,
)

selected_summary = summary_df.loc[summary_df["slug"].astype(str) == str(selected_slug)].iloc[0]
selected_links = (
    links_df.loc[links_df["slug"].astype(str) == str(selected_slug)]
    .drop_duplicates(subset=["platform", "video_link"])
    .sort_values(["platform", "video_link"])
    .copy()
)

if sidebar_mode == "Visão geral":
    total = len(summary_df)
    with_video = int((summary_df["video_links_found_total"] > 0).sum())
    integral_count = int((summary_df["integrity_status"] == "integro").sum())
    available_df, availability_groups, availability_reasons = build_availability_summary(summary_df)
    archive_type_counts = build_archive_type_summary(summary_df)
    _, visibility_counts = build_visibility_summary(summary_df)
    unavailable_count = int((available_df["availability_group"] == "Indisponível").sum())
    website_count = int(summary_df["website_available"].fillna(False).astype(bool).sum())
    detected_sites_df = build_detected_sites_df(summary_df, links_df)
    continent_counts, country_counts = build_geography_summaries(detected_sites_df)
    platform_counts = build_platform_summary(links_df)
    video_catalog_df = build_video_catalog_df(links_df)
    theme_counts = build_theme_summary(video_catalog_df)
    theme_country_counts = build_theme_country_summary(video_catalog_df)
    theme_country_matrix = build_theme_country_matrix(video_catalog_df)
    theme_platform_counts = build_theme_platform_summary(video_catalog_df)
    theme_archive_type_counts = build_theme_archive_type_summary(video_catalog_df, summary_df)
    theme_archive_type_matrix = build_theme_archive_type_matrix(video_catalog_df, summary_df)
    visibility_archive_type_counts = build_visibility_archive_type_summary(summary_df)
    visibility_archive_type_matrix = build_visibility_archive_type_matrix(summary_df)
    availability_reference_df = build_availability_reference()

    metric_cols = st.columns(4)
    metric_cols[0].metric("Instituições APE", total)
    metric_cols[1].metric("Com webpage externa", website_count)
    metric_cols[2].metric("Sites íntegros", integral_count)
    metric_cols[3].metric("Com links de vídeo", with_video)

    available_with_video_count = int((segmented_summary_df["institution_segment"] == "Disponíveis com vídeos").sum())

    st.info(
        "Nesta etapa, o APE funciona como base institucional principal e como corpus "
        "predominantemente de arquivos gerais. A aplicação verifica a ficha da instituição no "
        "portal e depois testa o site externo informado em `Webpage`."
    )
    st.caption(
        f"Nesta interface, toda instituição com vídeo detectado entra em `Disponíveis com vídeos` "
        f"({available_with_video_count} no total), mesmo quando o site atual exige ressalva de integridade."
    )

    tab_project, tab_dashboard, tab_sites, tab_videos, tab_geo, tab_base = st.tabs(
        [
            "Projeto",
            "Painel",
            f"Instituições com links de vídeo ({with_video})",
            f"Catálogo de vídeos ({len(video_catalog_df)})",
            "Geografia",
            "Base consolidada",
        ]
    )

    with tab_project:
        st.subheader("Sobre o projeto")
        st.markdown(
            """
            Este observatório investiga a visibilidade pública do audiovisual em ambientes arquivísticos na web.
            Nesta etapa, o corpus é formado pelo **Archives Portal Europe (APE)**, tratado como um portal
            arquivístico geral, e não como um repositório especializado em audiovisual.

            **Objetivo**

            Examinar como o audiovisual se torna publicamente visível, detectável e acessível nos sites
            institucionais vinculados ao APE, considerando tanto a presença explícita quanto formas mais
            indiretas de evidência.

            **Princípio metodológico**

            A ausência de vídeo detectado não autoriza afirmar, por si só, ausência de acervo audiovisual.
            No contexto de um portal geral, a não detecção pode indicar pelo menos quatro situações:

            - o acervo audiovisual pode não existir;
            - o acervo pode existir, mas não estar digitalizado;
            - o acervo pode estar digitalizado, mas não público;
            - o acervo pode estar público, porém pouco visível ou não detectável com a estratégia atual de coleta.

            **O que a plataforma afirma com maior segurança**

            - quando há evidência pública detectável de audiovisual;
            - quando há apenas evidência pública indireta;
            - quando não foi encontrada evidência pública detectável de audiovisual;
            - quando o site não pôde ser verificado.

            **O que a plataforma evita afirmar**

            - que a ausência de evidência pública detectável equivale à inexistência de acervo audiovisual;
            - que todo arquivo geral deva colocar o audiovisual em destaque na sua mediação institucional;
            - que classificações institucionais inferidas a partir do nome substituam a tipologia declarada na fonte.

            **Fonte institucional utilizada**

            Sempre que possível, a caracterização institucional é baseada no campo `Type of archive` declarado
            no próprio APE. Isso preserva maior rigor do que classificações heurísticas construídas apenas a
            partir do nome da instituição.
            """
        )

    with tab_dashboard:
        left, right = st.columns([1.2, 1])

        with left:
            st.subheader("Integridade dos sites institucionais")
            integrity_counts = (
                summary_df["integrity_status"]
                .value_counts()
                .rename_axis("integrity_status")
                .reset_index(name="total")
            )
            st.bar_chart(integrity_counts.set_index("integrity_status"))

            st.subheader("Disponibilidade: categorias e subcategorias")
            category_left, category_right = st.columns(2)
            with category_left:
                st.caption("Categorias")
                st.dataframe(availability_groups, use_container_width=True, hide_index=True)
            with category_right:
                st.caption("Subcategorias")
                st.dataframe(availability_reasons, use_container_width=True, hide_index=True)

            st.subheader("Referência de classificação")
            st.dataframe(availability_reference_df, use_container_width=True, hide_index=True)

            st.subheader("Casos indisponíveis")
            unavailable_df = available_df.loc[
                available_df["availability_group"] == "Indisponível"
            ].sort_values(
                ["integrity_status", "status", "video_links_found_total", "embedded_video_signals_total"],
                ascending=[True, True, False, False],
            )
            st.dataframe(
                unavailable_df[
                    [
                        "institution",
                        "archive_type",
                        "availability_reason",
                        "integrity_status",
                        "status",
                        "website_available",
                        "video_links_found_total",
                        "partner_domain",
                        "warning",
                    ]
                ],
                use_container_width=True,
            )

            broken_df = summary_df.loc[
                summary_df["integrity_status"].isin(["quebrado", "suspeito"]),
                [
                    "institution",
                    "archive_type",
                    "integrity_status",
                    "final_url",
                    "warning",
                    "status",
                    "partner_domain",
                ],
            ].copy()
            st.subheader("Detalhamento da categoria quebrado")
            st.caption(
                "Esta categoria inclui dois tipos de indisponibilidade: "
                "`quebrado (erro explícito)`, quando o site retorna falha clara como 404/410/5xx, "
                "e `quebrado (página suspeita)`, quando o site responde, mas cai em página genérica, "
                "suspensa, placeholder ou erro disfarçado."
            )
            if broken_df.empty:
                st.info("Nenhum caso enquadrado como quebrado foi detectado nesta rodada.")
            else:
                st.dataframe(broken_df, use_container_width=True)

            unstable_df = summary_df.loc[
                summary_df["integrity_status"] == "instavel",
                [
                    "institution",
                    "archive_type",
                    "status",
                    "error",
                    "partner_domain",
                    "final_url",
                ],
            ].copy()
            unstable_df["subcategoria_instavel"] = unstable_df.apply(classify_availability_reason, axis=1)
            st.subheader("Detalhamento da categoria instável")
            st.caption(
                "Instável reúne casos em que não houve resposta confiável do site, mesmo sem erro HTTP explícito."
            )
            if unstable_df.empty:
                st.info("Nenhum caso instável foi detectado nesta rodada.")
            else:
                st.dataframe(
                    unstable_df[
                        [
                            "institution",
                            "archive_type",
                            "subcategoria_instavel",
                            "status",
                            "error",
                            "partner_domain",
                            "final_url",
                        ]
                    ],
                    use_container_width=True,
                )

        with right:
            st.subheader("Plataformas detectadas")
            if not platform_counts.empty:
                st.bar_chart(platform_counts.set_index("platform"))
            else:
                st.info("Nenhum link de vídeo foi detectado ainda.")

            st.subheader("Temas dos vídeos")
            st.caption("Esta distribuição exclui, por padrão, ruído de plataforma ou incorporação externa.")
            if not theme_counts.empty:
                st.metric("Vídeos classificados na análise temática", int(theme_counts["total"].sum()))
                st.dataframe(theme_counts, use_container_width=True, hide_index=True)
            else:
                st.info("Ainda não há temas classificados para os vídeos.")

            st.subheader("Visibilidade do audiovisual")
            st.caption(
                "Em um portal geral como o APE, esta leitura distingue evidência pública detectável, "
                "evidência indireta, ausência de evidência pública e casos em que o site não pôde ser verificado."
            )
            if not visibility_counts.empty:
                st.dataframe(visibility_counts, use_container_width=True, hide_index=True)
            else:
                st.info("Ainda não há dados suficientes para analisar a visibilidade do audiovisual.")

            st.subheader("Tipo institucional declarado no APE")
            st.caption(
                "Distribuição baseada no campo `Type of archive` informado pela própria fonte institucional."
            )
            if not archive_type_counts.empty:
                st.dataframe(archive_type_counts, use_container_width=True, hide_index=True)
            else:
                st.info("Ainda não há dados suficientes para resumir o tipo institucional declarado no APE.")

            st.subheader("Tema x país")
            st.caption(
                "Matriz com os principais países e os temas mais frequentes, excluindo ruído de plataforma."
            )
            if not theme_country_matrix.empty:
                st.dataframe(
                    style_matrix_display(prepare_matrix_display(theme_country_matrix)),
                    use_container_width=True,
                    hide_index=True,
                )
            elif not theme_country_counts.empty:
                st.dataframe(theme_country_counts, use_container_width=True, hide_index=True)
            else:
                st.info("Ainda não há dados suficientes para cruzar temas e países.")

            st.subheader("Tema x plataforma")
            st.caption("Este cruzamento exclui, por padrão, ruído de plataforma ou incorporação externa.")
            if not theme_platform_counts.empty:
                st.dataframe(theme_platform_counts, use_container_width=True, hide_index=True)
            else:
                st.info("Ainda não há dados suficientes para cruzar temas e plataformas.")

            st.subheader("Tema x tipo de arquivo")
            st.caption(
                "Matriz entre temas dos vídeos e o `Type of archive` declarado no APE."
            )
            st.caption(
                "Leitura: as linhas representam tipos institucionais e as colunas representam temas; "
                "valores mais altos indicam maior concentração relativa naquele cruzamento."
            )
            if not theme_archive_type_matrix.empty:
                st.dataframe(
                    style_matrix_display(prepare_matrix_display(theme_archive_type_matrix)),
                    use_container_width=True,
                    hide_index=True,
                )
            elif not theme_archive_type_counts.empty:
                st.dataframe(theme_archive_type_counts, use_container_width=True, hide_index=True)
            else:
                st.info("Ainda não há dados suficientes para cruzar temas e tipos institucionais.")

            st.subheader("Visibilidade x tipo de arquivo")
            st.caption(
                "Matriz entre a situação metodológica do audiovisual e o tipo institucional declarado no APE."
            )
            st.caption(
                "Leitura: as linhas representam tipos institucionais e as colunas representam situações "
                "metodológicas; isso ajuda a comparar onde o audiovisual aparece, se torna opaco ou não pôde ser verificado."
            )
            if not visibility_archive_type_matrix.empty:
                st.dataframe(
                    style_matrix_display(prepare_matrix_display(visibility_archive_type_matrix)),
                    use_container_width=True,
                    hide_index=True,
                )
            elif not visibility_archive_type_counts.empty:
                st.dataframe(visibility_archive_type_counts, use_container_width=True, hide_index=True)
            else:
                st.info("Ainda não há dados suficientes para cruzar visibilidade e tipos institucionais.")

            st.subheader("Arquivos gerados")
            for file_path in sorted(OUTPUT_DIR.glob("ape_*")):
                st.write(file_path.name)

            st.metric("Indisponíveis", unavailable_count)
            st.caption(
                "Dentro de `quebrado`, a aplicação distingue erro explícito e página suspeita."
            )

    with tab_sites:
        st.subheader(f"Instituições com links de vídeo detectados ({with_video})")
        if detected_sites_df.empty:
            st.info("Nenhum link de vídeo foi detectado ainda nos sites das instituições do APE.")
        else:
            st.dataframe(
                detected_sites_df[
                    [
                        "institution",
                        "archive_type",
                        "integrity_status",
                        "video_links_found_total",
                        "embedded_video_signals_total",
                        "platforms_detectadas",
                        "country",
                        "continent",
                        "partner_domain",
                        "warning",
                        "final_url",
                    ]
                ],
                use_container_width=True,
            )

            for _, row in detected_sites_df.iterrows():
                with st.expander(row["institution"]):
                    render_integrity_badge(row["integrity_status"])
                    st.write(f"Categoria: {classify_availability_group(row['integrity_status'])}")
                    st.write(f"Subcategoria: {classify_availability_reason(row)}")
                    if pd.notna(row.get("archive_type")) and str(row.get("archive_type")).strip():
                        st.write(f"Tipo de arquivo: {row['archive_type']}")
                    st.write(f"Domínio: {row['partner_domain']}")
                    st.write(f"Status técnico: {row['status']}")
                    st.write(f"Links de vídeo: {int(row['video_links_found_total'])}")
                    st.write(f"Sinais embutidos: {int(row['embedded_video_signals_total'])}")
                    if row["platforms_detectadas"]:
                        st.write(f"Plataformas detectadas: {row['platforms_detectadas']}")
                    if pd.notna(row.get("warning")) and str(row.get("warning")).strip():
                        st.warning(str(row["warning"]))
                    if pd.notna(row.get("ape_detail_url")) and str(row.get("ape_detail_url")).strip():
                        st.markdown(f"[Abrir ficha no APE]({row['ape_detail_url']})")
                    st.markdown(f"[Abrir site institucional]({row['final_url']})")

    with tab_videos:
        st.subheader("Catálogo de vídeos detectados")
        if video_catalog_df.empty:
            st.info("Nenhum link de vídeo foi detectado ainda nos sites das instituições do APE.")
        else:
            st.markdown(
                "Este catálogo organiza os vídeos detectados a partir de metadados básicos e de uma "
                "classificação temática inicial baseada em título, assunto e descrição."
            )

            overview_cols = st.columns(3)
            overview_cols[0].metric("Vídeos detectados", len(video_catalog_df))
            overview_cols[1].metric("Temas mapeados", int(video_catalog_df["video_theme"].nunique()))
            overview_cols[2].metric("Plataformas", int(video_catalog_df["platform"].nunique()))

            st.markdown("#### Distribuição temática")
            if not theme_counts.empty:
                st.dataframe(theme_counts, use_container_width=True, hide_index=True)

            filter_cols = st.columns(2)
            video_platforms = sorted(video_catalog_df["platform"].dropna().unique().tolist())
            with filter_cols[0]:
                selected_platforms = st.multiselect(
                    "Plataformas",
                    options=video_platforms,
                    default=video_platforms,
                )
            available_continents = sorted(
                video_catalog_df["continent"].fillna("Não classificado").replace("", "Não classificado").unique().tolist()
            )
            with filter_cols[1]:
                selected_continents = st.multiselect(
                    "Continentes",
                    options=available_continents,
                    default=available_continents,
                )

            if selected_sidebar_theme == "Todos os temas":
                selected_themes = [
                    theme
                    for theme in video_catalog_df["video_theme"].dropna().unique().tolist()
                    if theme != "Ruído de plataforma ou incorporação externa"
                ]
            else:
                selected_themes = [selected_sidebar_theme]

            filtered_videos = video_catalog_df[
                video_catalog_df["platform"].isin(selected_platforms)
                & video_catalog_df["continent"].fillna("Não classificado").replace("", "Não classificado").isin(selected_continents)
                & video_catalog_df["video_theme"].isin(selected_themes)
            ].copy()

            st.caption(f"Tema selecionado na barra lateral: {selected_sidebar_theme}.")
            st.caption(f"{len(filtered_videos)} vídeos no recorte atual.")

            video_view_mode = st.radio(
                "Organização dos vídeos",
                options=["Por tema", "Tabela"],
                horizontal=True,
            )

            if video_view_mode == "Tabela":
                st.dataframe(
                    filtered_videos[
                        [
                            "institution",
                            "platform",
                            "video_theme",
                            "video_title_display",
                            "video_date_display",
                            "country",
                            "continent",
                            "video_link",
                        ]
                    ].rename(
                        columns={
                            "video_theme": "tema",
                            "video_title_display": "título",
                            "video_date_display": "data",
                            "institution": "instituição",
                            "platform": "plataforma",
                            "country": "país",
                            "continent": "continente",
                            "video_link": "link",
                        }
                    ),
                    use_container_width=True,
                )
            else:
                if filtered_videos.empty:
                    st.info("Nenhum vídeo corresponde ao tema e aos filtros selecionados.")
                else:
                    theme_order = filtered_videos["video_theme"].value_counts().index.tolist()
                    expand_selected_theme = selected_sidebar_theme != "Todos os temas"
                    for theme_name in theme_order:
                        theme_subset = filtered_videos.loc[
                            filtered_videos["video_theme"] == theme_name
                        ].copy()
                        theme_subset = theme_subset.sort_values(
                            ["institution", "platform", "video_date_display", "video_title_display"],
                            ascending=[True, True, False, True],
                        )
                        with st.expander(
                            f"{theme_name} ({len(theme_subset)})",
                            expanded=expand_selected_theme,
                        ):
                            for _, row in theme_subset.iterrows():
                                st.markdown(f"**{row['video_title_display']}**")
                                st.caption(
                                    f"{row['institution']} | {row['platform']} | "
                                    f"{normalize_text(row['country'])} | {normalize_text(row['video_date_display'])}"
                                )
                                st.markdown(f"[Abrir vídeo]({row['video_link']})")
                                st.code(row["video_link"], language=None)

            with st.expander("Ver distribuição temática", expanded=False):
                st.caption("A distribuição temática apresentada aqui exclui o ruído de plataforma da análise.")
                if not theme_counts.empty:
                    st.dataframe(theme_counts, use_container_width=True, hide_index=True)
                else:
                    st.info("Ainda não há temas classificados para os vídeos.")

    with tab_geo:
        st.subheader("Organização geográfica das instituições com conteúdo audiovisual detectado")
        geo_left, geo_right = st.columns(2)

        with geo_left:
            if not continent_counts.empty:
                st.caption("Distribuição por continente")
                st.bar_chart(continent_counts.set_index("continent"))
            else:
                st.info("Ainda não há distribuição geográfica com links de vídeo detectados.")

        with geo_right:
            if not country_counts.empty:
                st.caption("Distribuição por país")
                st.bar_chart(country_counts.set_index("country"))

        continent_filter = st.multiselect(
            "Filtrar continentes",
            options=continent_counts["continent"].tolist(),
            default=continent_counts["continent"].tolist(),
        )
        geo_filtered = detected_sites_df[
            detected_sites_df["continent"]
            .fillna("Não classificado")
            .replace("", "Não classificado")
            .isin(continent_filter)
        ]
        st.dataframe(
            geo_filtered[
                [
                    "institution",
                    "archive_type",
                    "continent",
                    "country",
                    "integrity_status",
                    "video_links_found_total",
                    "platforms_detectadas",
                    "final_url",
                ]
            ],
            use_container_width=True,
        )

    with tab_base:
        st.subheader("Base consolidada do APE")
        st.caption(
            "Cada linha representa uma instituição listada no APE com conteúdo publicado, complementada "
            "pela verificação do site externo informado na ficha do portal."
        )
        integrity_filter = st.multiselect(
            "Filtrar por integridade",
            options=sorted(summary_df["integrity_status"].dropna().unique().tolist()),
            default=sorted(summary_df["integrity_status"].dropna().unique().tolist()),
        )
        filtered = summary_df[summary_df["integrity_status"].isin(integrity_filter)]
        filtered = filtered.copy()
        filtered["audiovisual_visibility"] = filtered.apply(classify_audiovisual_visibility, axis=1)
        st.dataframe(filtered, use_container_width=True)

else:
    st.subheader(selected_summary["institution"])
    col1, col2, col3 = st.columns([1, 1, 2])
    with col1:
        st.caption("Integridade")
        render_integrity_badge(selected_summary["integrity_status"])
    with col2:
        st.caption("Status técnico")
        st.write(selected_summary["status"])
    with col3:
        st.caption("Ficha da instituição no APE")
        if pd.notna(selected_summary.get("ape_detail_url")) and str(selected_summary.get("ape_detail_url")).strip():
            st.markdown(f"[{selected_summary['ape_detail_url']}]({selected_summary['ape_detail_url']})")
        else:
            st.write("-")

    geo_cols = st.columns(4)
    geo_cols[0].metric("País", selected_summary["country"] if pd.notna(selected_summary["country"]) and selected_summary["country"] else "-")
    geo_cols[1].metric(
        "Continente",
        selected_summary["continent"] if pd.notna(selected_summary["continent"]) and selected_summary["continent"] else "Não classificado",
    )
    geo_cols[2].metric(
        "Tipo de arquivo",
        selected_summary["archive_type"] if pd.notna(selected_summary["archive_type"]) and selected_summary["archive_type"] else "-",
    )
    geo_cols[3].metric(
        "Webpage no APE",
        "Sim" if bool(selected_summary.get("website_available")) else "Não",
    )

    info_cols = st.columns(4)
    info_cols[0].metric("HTTP", selected_summary["http_code"] if pd.notna(selected_summary["http_code"]) else "-")
    info_cols[1].metric("Links de vídeo", int(selected_summary["video_links_found_total"]))
    info_cols[2].metric("Sinais embutidos", int(selected_summary["embedded_video_signals_total"]))
    info_cols[3].metric("Páginas internas", int(selected_summary["candidate_internal_pages"]))

    st.markdown("### Página da instituição")
    if selected_summary["integrity_status"] in {"integro", "acessivel"}:
        st.success("O site externo respondeu. Esta instituição pode seguir para curadoria pública.")
    elif selected_summary["integrity_status"] == "suspeito":
        st.warning("O site respondeu, mas a página final parece genérica, suspensa ou não confiável. Aqui ele entra dentro da categoria quebrado.")
    elif selected_summary["integrity_status"] == "restrito":
        st.warning("O site respondeu com restrição de acesso. Para o projeto, ele entra como não disponível.")
    elif selected_summary["integrity_status"] == "sem_site":
        st.warning("A ficha no APE não informa uma webpage externa para esta instituição.")
    else:
        st.error("O site institucional não respondeu de forma confiável. Para o projeto, esta instituição entra como não disponível.")

    st.caption(f"Categoria: {classify_availability_group(selected_summary['integrity_status'])}")
    st.caption(f"Subcategoria: {classify_availability_reason(selected_summary)}")
    st.caption(f"Situação metodológica do audiovisual: {classify_audiovisual_visibility(selected_summary)}")

    if pd.notna(selected_summary.get("warning")) and str(selected_summary.get("warning")).strip():
        st.info(str(selected_summary["warning"]))

    if pd.notna(selected_summary.get("final_url")) and str(selected_summary.get("final_url")).strip():
        st.markdown("### Site institucional")
        st.markdown(f"[{selected_summary['final_url']}]({selected_summary['final_url']})")

    st.markdown("### Links de vídeo encontrados")
    if selected_links.empty:
        st.info("Nenhum link de vídeo foi detectado automaticamente para esta instituição.")
    else:
        for _, row in selected_links.iterrows():
            title = normalize_optional_text(row.get("video_title")) or normalize_optional_text(row.get("video_subject")) or row["video_link"]
            published_at = format_video_date(row.get("video_published_at"))
            theme_label = infer_video_theme(row)
            st.markdown(f"**{normalize_text(row['platform'])}**")
            st.write(title)
            st.caption(f"Tema sugerido: {theme_label}")
            if published_at:
                st.caption(f"Publicado em {published_at}")
            description = normalize_optional_text(row.get("video_description"))
            if description:
                st.write(description)
            st.link_button(f"Abrir {row['video_link']}", row["video_link"])
            if "youtube.com" in row["video_link"] or "youtu.be" in row["video_link"]:
                st.video(row["video_link"])
            else:
                vimeo_embed = get_vimeo_embed_url(row["video_link"])
                if vimeo_embed:
                    components.iframe(vimeo_embed, height=360)
            st.code(row["video_link"], language=None)

    if not internal_df.empty:
        selected_internal = internal_df.loc[internal_df["slug"].astype(str) == str(selected_slug)]
        if not selected_internal.empty:
            st.markdown("### Páginas internas analisadas")
            st.dataframe(selected_internal, use_container_width=True)
