import re
import unicodedata

import pandas as pd


NOISE_THEME_LABEL = "Ruído de plataforma ou incorporação externa"
UNCLASSIFIED_LABEL = "Não classificado"
UNKNOWN_ARCHIVE_TYPE_LABEL = "Não informado no APE"


def normalize_text(value, fallback="-"):
    if pd.isna(value):
        return fallback
    text = str(value).strip()
    return text if text else fallback


def normalize_optional_text(value):
    if pd.isna(value):
        return ""
    return str(value).strip()


def format_video_date(value):
    text = normalize_optional_text(value)
    if not text:
        return ""
    parsed = pd.to_datetime(text, errors="coerce", utc=True)
    if pd.isna(parsed):
        return text
    return parsed.strftime("%Y-%m-%d")


def normalize_for_matching(value):
    text = normalize_optional_text(value).lower()
    text = unicodedata.normalize("NFKD", text)
    text = "".join(char for char in text if not unicodedata.combining(char))
    return text


def text_has_any_keyword(text, keywords):
    return any(keyword in text for keyword in keywords)


def infer_video_theme(row):
    combined_text = " ".join(
        [
            normalize_optional_text(row.get("video_title")),
            normalize_optional_text(row.get("video_subject")),
            normalize_optional_text(row.get("video_description")),
        ]
    )
    normalized = normalize_for_matching(combined_text)

    noise_patterns = [
        "provided to youtube",
        "auto-generated by youtube",
        "youtube",
        "topic",
        "vevo",
        "official audio",
        "official music video",
        "licensed to youtube",
    ]
    if text_has_any_keyword(normalized, noise_patterns):
        return NOISE_THEME_LABEL

    theme_rules = [
        (
            "Apresentação institucional",
            [
                "imagefilm",
                "moodfilm",
                "promo",
                "promotional",
                "introduction",
                "introduct",
                "archive tour",
                "about the archive",
                "about us",
                "presentation",
                "presentatie",
                "presentation du service",
                "institutional",
                "a propos",
                "qui sommes",
                "uber uns",
                "welcome to",
                "mission",
                "who we are",
                "our archive",
                "our archives",
            ],
        ),
        (
            "Visita e descoberta do arquivo",
            [
                "discover",
                "discover our",
                "visit us",
                "visite",
                "tour",
                "guided tour",
                "virtual tour",
                "walkthrough",
                "behind the scenes",
                "open day",
                "journees du patrimoine",
                "portes ouvertes",
                "open house",
            ],
        ),
        (
            "Divulgação de serviços e projetos",
            [
                "campaign",
                "launch",
                "announcement",
                "annonce",
                "highlights",
                "promotion",
                "project",
                "initiative",
                "service",
                "services",
                "program",
                "programme",
                "platform",
                "tool",
                "resource",
                "new website",
                "new portal",
            ],
        ),
        (
            "Comunicação institucional",
            [
                "spot",
                "teaser",
                "trailer",
                "promo clip",
                "institutional communication",
                "message from",
                "greetings",
                "statement",
                "address by",
                "news",
                "newsletter",
            ],
        ),
        (
            "Digitalização e acesso",
            [
                "digit",
                "digitalis",
                "digitaliz",
                "online",
                "search",
                "zoeken",
                "catalog",
                "catalogue",
                "http://search.",
                "zoek",
                "database",
                "portal",
                "scan",
                "metadata",
                "open data",
                "access",
                "consultation",
                "discovery",
                "finder",
            ],
        ),
        (
            "Coleções e serviços",
            [
                "collection",
                "collections",
                "collectie",
                "sammlung",
                "fonds",
                "archive holdings",
                "services",
                "reading room",
                "record office",
                "kadaster",
                "inventar",
                "inventaire",
                "manuscript",
                "manuscripts",
                "photograph",
                "photographs",
                "special collections",
                "library",
                "bibliotheek",
                "bibliotheque",
                "map collection",
                "photo archive",
                "film archive",
                "sound archive",
            ],
        ),
        (
            "Preservação e conservação",
            [
                "preservation",
                "conservation",
                "restoration",
                "restaur",
                "preserv",
                "conserv",
                "film preservation",
                "storage",
                "repair",
                "climate",
                "vault",
            ],
        ),
        (
            "Formação e mediação",
            [
                "tutorial",
                "instructievideo",
                "instruction",
                "how to",
                "workshop",
                "academy",
                "teaching",
                "learning",
                "education",
                "didactic",
                "mediation",
                "lesson",
                "course",
                "seminar",
                "classroom",
                "pedagog",
            ],
        ),
        (
            "Exposições e eventos",
            [
                "exhibition",
                "expo",
                "festival",
                "event",
                "conference",
                "symposium",
                "vernissage",
                "opening",
                "programma",
                "programme",
                "program",
                "journee",
                "tagung",
                "celebration",
                "anniversary",
            ],
        ),
        (
            "Música e performance",
            [
                "music",
                "musica",
                "muziek",
                "soundpainting",
                "concert",
                "performance",
                "orchestra",
                "choir",
                "opera",
                "live",
                "theatre",
                "theater",
                "dance",
                "stage",
            ],
        ),
        (
            "Memória, narrativa e testemunho",
            [
                "oral history",
                "testimony",
                "testimonial",
                "memoir",
                "memories",
                "souvenir",
                "witness",
                "interview",
                "story",
                "narrative",
                "remembrance",
                "legacy",
                "biography",
                "life story",
            ],
        ),
        (
            "História e pesquisa",
            [
                "history",
                "histor",
                "research",
                "study",
                "patrimony",
                "heritage",
                "erfgoed",
                "past",
                "war",
                "archive research",
                "historical",
                "geschichte",
                "histoire",
                "historie",
                "scholar",
                "academic",
                "documentary",
                "heritage studies",
            ],
        ),
        (
            "Acervo e patrimônio",
            [
                "archive",
                "archiv",
                "archives",
                "archivo",
                "arxiu",
                "heritage",
                "patrimoine",
                "patrimonio",
                "erfgoed",
                "memory",
                "memoire",
                "memoria",
                "municipal",
                "state archive",
                "city archive",
                "national archive",
                "regional archive",
                "historical archive",
                "library and archives",
                "cultural heritage",
                "documentary heritage",
                "archive collection",
            ],
        ),
        (
            "Memória institucional",
            [
                "memory of the institution",
                "institutional memory",
                "history of the archive",
                "archive history",
                "history of the institution",
                "our history",
                "legacy of",
                "historique",
                "geschichte des archivs",
            ],
        ),
    ]

    for theme_name, keywords in theme_rules:
        if text_has_any_keyword(normalized, keywords):
            return theme_name

    if re.search(r"\b(memory|memoria|memoire|legacy|historique)\b", normalized):
        return "Memória institucional"
    if re.search(
        r"\b(archive|archiv|archivo|arxiu|archives|heritage|library|patrimoine|patrimonio|erfgoed)\b",
        normalized,
    ):
        return "Acervo e patrimônio"
    if re.search(r"\b(visit|tour|discover|open day|portes ouvertes|open house)\b", normalized):
        return "Visita e descoberta do arquivo"
    if re.search(
        r"\b(project|service|platform|portal|resource|tool|initiative|launch|announcement)\b",
        normalized,
    ):
        return "Divulgação de serviços e projetos"
    if normalized.strip():
        return "Comunicação institucional"
    return "Tema não identificado"


def build_detected_sites_df(summary_df, links_df):
    if summary_df.empty:
        return summary_df.copy()

    ranked = summary_df.copy()
    ranked["video_links_found_total"] = pd.to_numeric(
        ranked.get("video_links_found_total", 0),
        errors="coerce",
    ).fillna(0)
    ranked["embedded_video_signals_total"] = pd.to_numeric(
        ranked.get("embedded_video_signals_total", 0),
        errors="coerce",
    ).fillna(0)
    ranked = ranked.loc[ranked["video_links_found_total"] > 0].copy()
    if ranked.empty:
        return ranked

    platforms_df = pd.DataFrame(columns=["slug", "platforms_detectadas"])
    if not links_df.empty:
        platforms_df = (
            links_df.groupby("slug")["platform"]
            .apply(lambda values: ", ".join(sorted(pd.unique(values))))
            .reset_index(name="platforms_detectadas")
        )

    ranked = ranked.merge(platforms_df, on="slug", how="left")
    ranked["platforms_detectadas"] = ranked["platforms_detectadas"].fillna("")
    return ranked.sort_values(
        [
            "video_links_found_total",
            "embedded_video_signals_total",
            "integrity_status",
            "institution",
        ],
        ascending=[False, False, True, True],
    )


def build_geography_summaries(df):
    if df.empty:
        return (
            pd.DataFrame(columns=["continent", "instituicoes"]),
            pd.DataFrame(columns=["country", "instituicoes"]),
        )

    continent_counts = (
        df["continent"]
        .fillna(UNCLASSIFIED_LABEL)
        .replace("", UNCLASSIFIED_LABEL)
        .value_counts()
        .rename_axis("continent")
        .reset_index(name="instituicoes")
    )
    country_counts = (
        df["country"]
        .fillna(UNCLASSIFIED_LABEL)
        .replace("", UNCLASSIFIED_LABEL)
        .value_counts()
        .rename_axis("country")
        .reset_index(name="instituicoes")
    )
    return continent_counts, country_counts


def build_platform_summary(links_df):
    if links_df.empty:
        return pd.DataFrame(columns=["platform", "total"])
    return links_df["platform"].value_counts().rename_axis("platform").reset_index(name="total")


def classify_availability_group(integrity_status):
    status = normalize_optional_text(integrity_status)
    if status in {"integro", "acessivel"}:
        return "Disponível"
    return "Indisponível"


def classify_availability_reason(row):
    status = normalize_optional_text(row.get("integrity_status"))
    if status == "integro":
        return "Disponível: íntegro"
    if status == "acessivel":
        return "Disponível: acessível"
    if status == "suspeito":
        return "Indisponível: quebrado (página suspeita)"
    if status == "restrito":
        return "Indisponível: restrito"
    if status == "quebrado":
        return "Indisponível: quebrado (erro explícito)"
    if status == "instavel":
        error_text = normalize_optional_text(row.get("error")).lower()
        if "timeout" in error_text:
            return "Indisponível: instável (timeout ou falha de carregamento)"
        if error_text:
            return "Indisponível: instável (erro de navegação)"
        return "Indisponível: instável"
    if status == "sem_site":
        return "Indisponível: sem site"
    return "Indisponível: outro"


def build_availability_reference():
    return pd.DataFrame(
        [
            {
                "categoria": "Disponível",
                "subcategoria": "íntegro",
                "descricao": "O site respondeu de forma confiável e a página final parece válida.",
            },
            {
                "categoria": "Disponível",
                "subcategoria": "acessível",
                "descricao": "O site respondeu, mas sem sinal forte de integridade plena.",
            },
            {
                "categoria": "Indisponível",
                "subcategoria": "quebrado (erro explícito)",
                "descricao": "O site retornou erro claro, como 404, 410 ou 5xx.",
            },
            {
                "categoria": "Indisponível",
                "subcategoria": "quebrado (página suspeita)",
                "descricao": "O site respondeu, mas abriu página genérica, suspensa, placeholder ou erro disfarçado.",
            },
            {
                "categoria": "Indisponível",
                "subcategoria": "restrito",
                "descricao": "O acesso exige permissão, autenticação ou foi bloqueado.",
            },
            {
                "categoria": "Indisponível",
                "subcategoria": "instável (timeout ou falha de carregamento)",
                "descricao": "A página não carregou de forma confiável dentro do tempo esperado ou falhou durante a navegação.",
            },
            {
                "categoria": "Indisponível",
                "subcategoria": "instável (erro de navegação)",
                "descricao": "A navegação falhou sem código HTTP explícito, por erro de navegador, sessão ou carregamento.",
            },
            {
                "categoria": "Indisponível",
                "subcategoria": "sem site",
                "descricao": "A ficha no APE não informa webpage externa.",
            },
        ]
    )


def classify_audiovisual_visibility(row):
    status = normalize_optional_text(row.get("integrity_status"))
    video_links = pd.to_numeric(row.get("video_links_found_total"), errors="coerce")
    embedded_signals = pd.to_numeric(row.get("embedded_video_signals_total"), errors="coerce")
    internal_pages = pd.to_numeric(row.get("candidate_internal_pages"), errors="coerce")

    video_links = 0 if pd.isna(video_links) else int(video_links)
    embedded_signals = 0 if pd.isna(embedded_signals) else int(embedded_signals)
    internal_pages = 0 if pd.isna(internal_pages) else int(internal_pages)

    if video_links > 0:
        return "Evidência pública detectável de audiovisual"
    if embedded_signals > 0:
        return "Evidência pública indireta de audiovisual"
    if status in {"integro", "acessivel"} and internal_pages > 0:
        return "Potencial audiovisual em navegação interna"
    if status in {"integro", "acessivel"}:
        return "Sem evidência pública detectável de audiovisual"
    return "Site indisponível para verificação"


def build_summary_analysis_df(summary_df):
    enriched = summary_df.copy()
    if enriched.empty:
        for column in [
            "availability_group",
            "availability_reason",
            "audiovisual_visibility",
            "institution_segment",
        ]:
            if column not in enriched.columns:
                enriched[column] = pd.Series(dtype="object")
        return enriched

    enriched["availability_group"] = enriched["integrity_status"].apply(classify_availability_group)
    enriched["availability_reason"] = enriched.apply(classify_availability_reason, axis=1)
    enriched["audiovisual_visibility"] = enriched.apply(classify_audiovisual_visibility, axis=1)
    enriched["video_links_found_total"] = pd.to_numeric(
        enriched["video_links_found_total"],
        errors="coerce",
    ).fillna(0)
    enriched["institution_segment"] = "Indisponíveis"
    enriched.loc[
        enriched["video_links_found_total"] > 0,
        "institution_segment",
    ] = "Disponíveis com vídeos"
    enriched.loc[
        (enriched["availability_group"] == "Disponível")
        & (enriched["video_links_found_total"] <= 0),
        "institution_segment",
    ] = "Disponíveis sem vídeos"
    return enriched


def build_availability_summary(summary_df):
    enriched = build_summary_analysis_df(summary_df)
    group_counts = (
        enriched["availability_group"].value_counts().rename_axis("categoria").reset_index(name="total")
        if not enriched.empty
        else pd.DataFrame(columns=["categoria", "total"])
    )
    reason_counts = (
        enriched["availability_reason"].value_counts().rename_axis("subcategoria").reset_index(name="total")
        if not enriched.empty
        else pd.DataFrame(columns=["subcategoria", "total"])
    )
    return enriched, group_counts, reason_counts


def build_archive_type_summary(summary_df):
    if summary_df.empty or "archive_type" not in summary_df.columns:
        return pd.DataFrame(columns=["tipo_institucional", "total"])
    enriched = summary_df.copy()
    enriched["archive_type_display"] = (
        enriched["archive_type"]
        .fillna(UNKNOWN_ARCHIVE_TYPE_LABEL)
        .astype(str)
        .str.strip()
        .replace("", UNKNOWN_ARCHIVE_TYPE_LABEL)
    )
    return (
        enriched["archive_type_display"]
        .value_counts()
        .rename_axis("tipo_institucional")
        .reset_index(name="total")
    )


def build_visibility_summary(summary_df):
    enriched = build_summary_analysis_df(summary_df)
    visibility_counts = (
        enriched["audiovisual_visibility"].value_counts().rename_axis("situacao").reset_index(name="total")
        if not enriched.empty
        else pd.DataFrame(columns=["situacao", "total"])
    )
    return enriched, visibility_counts


def build_institution_segments(summary_df):
    return build_summary_analysis_df(summary_df)


def build_video_catalog_df(links_df):
    if links_df.empty:
        return pd.DataFrame(
            columns=[
                "institution",
                "platform",
                "video_title",
                "video_subject",
                "video_published_at",
                "country",
                "continent",
                "video_link",
            ]
        )

    catalog = links_df.copy()
    for column in ["video_title", "video_subject", "video_description", "video_published_at"]:
        if column not in catalog.columns:
            catalog[column] = ""

    catalog["video_title"] = catalog["video_title"].fillna("").astype(str).str.strip()
    catalog["video_subject"] = catalog["video_subject"].fillna("").astype(str).str.strip()
    catalog["video_published_at"] = catalog["video_published_at"].fillna("").astype(str).str.strip()
    catalog["video_title_display"] = catalog["video_title"]
    catalog.loc[catalog["video_title_display"] == "", "video_title_display"] = (
        catalog.loc[catalog["video_title_display"] == "", "video_subject"]
    )
    catalog.loc[catalog["video_title_display"] == "", "video_title_display"] = (
        catalog.loc[catalog["video_title_display"] == "", "video_link"]
    )
    catalog["video_date_display"] = catalog["video_published_at"].apply(format_video_date)
    catalog["video_theme"] = catalog.apply(infer_video_theme, axis=1)

    return catalog.sort_values(
        ["institution", "platform", "video_date_display", "video_title_display"],
        ascending=[True, True, False, True],
    )


def filter_curatorial_video_catalog(video_catalog_df):
    if video_catalog_df.empty or "video_theme" not in video_catalog_df.columns:
        return video_catalog_df.copy()
    return video_catalog_df.loc[video_catalog_df["video_theme"] != NOISE_THEME_LABEL].copy()


def _limit_summary(summary_df, top_n):
    if top_n is None:
        return summary_df
    return summary_df.head(top_n)


def build_theme_summary(video_catalog_df):
    filtered_catalog = filter_curatorial_video_catalog(video_catalog_df)
    if filtered_catalog.empty:
        return pd.DataFrame(columns=["tema", "total"])
    return filtered_catalog["video_theme"].value_counts().rename_axis("tema").reset_index(name="total")


def build_theme_country_summary(video_catalog_df, top_n=10):
    filtered_catalog = filter_curatorial_video_catalog(video_catalog_df)
    if filtered_catalog.empty:
        return pd.DataFrame(columns=["tema", "pais", "total"])
    summary = (
        filtered_catalog.assign(
            country=filtered_catalog["country"].fillna(UNCLASSIFIED_LABEL).replace("", UNCLASSIFIED_LABEL)
        )
        .groupby(["video_theme", "country"])
        .size()
        .reset_index(name="total")
        .sort_values(["total", "video_theme", "country"], ascending=[False, True, True])
        .rename(columns={"video_theme": "tema", "country": "pais"})
    )
    return _limit_summary(summary, top_n)


def build_theme_country_matrix(video_catalog_df, top_countries=10, top_themes=8):
    filtered_catalog = filter_curatorial_video_catalog(video_catalog_df)
    if filtered_catalog.empty:
        return pd.DataFrame()

    filtered_catalog["country_display"] = (
        filtered_catalog["country"].fillna(UNCLASSIFIED_LABEL).replace("", UNCLASSIFIED_LABEL)
    )
    top_country_values = filtered_catalog["country_display"].value_counts().head(top_countries).index.tolist()
    top_theme_values = filtered_catalog["video_theme"].value_counts().head(top_themes).index.tolist()

    matrix_source = filtered_catalog[
        filtered_catalog["country_display"].isin(top_country_values)
        & filtered_catalog["video_theme"].isin(top_theme_values)
    ].copy()
    if matrix_source.empty:
        return pd.DataFrame()

    matrix = pd.crosstab(matrix_source["country_display"], matrix_source["video_theme"])
    matrix = matrix.reindex(index=top_country_values, columns=top_theme_values, fill_value=0)
    matrix.index.name = "país"
    return matrix.reset_index()


def build_theme_platform_summary(video_catalog_df, top_n=10):
    filtered_catalog = filter_curatorial_video_catalog(video_catalog_df)
    if filtered_catalog.empty:
        return pd.DataFrame(columns=["tema", "plataforma", "total"])
    summary = (
        filtered_catalog.groupby(["video_theme", "platform"])
        .size()
        .reset_index(name="total")
        .sort_values(["total", "video_theme", "platform"], ascending=[False, True, True])
        .rename(columns={"video_theme": "tema", "platform": "plataforma"})
    )
    return _limit_summary(summary, top_n)


def build_theme_archive_type_summary(video_catalog_df, summary_df, top_n=12):
    if (
        video_catalog_df.empty
        or "video_theme" not in video_catalog_df.columns
        or summary_df.empty
        or "slug" not in summary_df.columns
    ):
        return pd.DataFrame(columns=["tema", "tipo_institucional", "total"])

    filtered_catalog = filter_curatorial_video_catalog(video_catalog_df)
    if filtered_catalog.empty:
        return pd.DataFrame(columns=["tema", "tipo_institucional", "total"])

    archive_lookup = summary_df[["slug", "archive_type"]].copy()
    archive_lookup["archive_type_display"] = (
        archive_lookup["archive_type"]
        .fillna(UNKNOWN_ARCHIVE_TYPE_LABEL)
        .astype(str)
        .str.strip()
        .replace("", UNKNOWN_ARCHIVE_TYPE_LABEL)
    )

    merged = filtered_catalog.merge(
        archive_lookup[["slug", "archive_type_display"]],
        on="slug",
        how="left",
    )
    summary = (
        merged.groupby(["video_theme", "archive_type_display"])
        .size()
        .reset_index(name="total")
        .sort_values(["total", "video_theme", "archive_type_display"], ascending=[False, True, True])
        .rename(columns={"video_theme": "tema", "archive_type_display": "tipo_institucional"})
    )
    return _limit_summary(summary, top_n)


def build_theme_archive_type_matrix(video_catalog_df, summary_df, top_archive_types=8, top_themes=8):
    if (
        video_catalog_df.empty
        or "video_theme" not in video_catalog_df.columns
        or summary_df.empty
        or "slug" not in summary_df.columns
    ):
        return pd.DataFrame()

    filtered_catalog = filter_curatorial_video_catalog(video_catalog_df)
    if filtered_catalog.empty:
        return pd.DataFrame()

    archive_lookup = summary_df[["slug", "archive_type"]].copy()
    archive_lookup["archive_type_display"] = (
        archive_lookup["archive_type"]
        .fillna(UNKNOWN_ARCHIVE_TYPE_LABEL)
        .astype(str)
        .str.strip()
        .replace("", UNKNOWN_ARCHIVE_TYPE_LABEL)
    )

    merged = filtered_catalog.merge(
        archive_lookup[["slug", "archive_type_display"]],
        on="slug",
        how="left",
    )
    top_archive_type_values = merged["archive_type_display"].value_counts().head(top_archive_types).index.tolist()
    top_theme_values = merged["video_theme"].value_counts().head(top_themes).index.tolist()

    matrix_source = merged[
        merged["archive_type_display"].isin(top_archive_type_values)
        & merged["video_theme"].isin(top_theme_values)
    ].copy()
    if matrix_source.empty:
        return pd.DataFrame()

    matrix = pd.crosstab(matrix_source["archive_type_display"], matrix_source["video_theme"])
    matrix = matrix.reindex(index=top_archive_type_values, columns=top_theme_values, fill_value=0)
    matrix.index.name = "tipo_institucional"
    return matrix.reset_index()


def build_visibility_archive_type_summary(summary_df, top_n=12):
    if summary_df.empty:
        return pd.DataFrame(columns=["visibilidade", "tipo_institucional", "total"])

    enriched = build_summary_analysis_df(summary_df)
    enriched["archive_type_display"] = (
        enriched["archive_type"]
        .fillna(UNKNOWN_ARCHIVE_TYPE_LABEL)
        .astype(str)
        .str.strip()
        .replace("", UNKNOWN_ARCHIVE_TYPE_LABEL)
    )

    summary = (
        enriched.groupby(["audiovisual_visibility", "archive_type_display"])
        .size()
        .reset_index(name="total")
        .sort_values(["total", "audiovisual_visibility", "archive_type_display"], ascending=[False, True, True])
        .rename(columns={"audiovisual_visibility": "visibilidade", "archive_type_display": "tipo_institucional"})
    )
    return _limit_summary(summary, top_n)


def build_visibility_archive_type_matrix(summary_df, top_archive_types=8):
    if summary_df.empty:
        return pd.DataFrame()

    enriched = build_summary_analysis_df(summary_df)
    enriched["archive_type_display"] = (
        enriched["archive_type"]
        .fillna(UNKNOWN_ARCHIVE_TYPE_LABEL)
        .astype(str)
        .str.strip()
        .replace("", UNKNOWN_ARCHIVE_TYPE_LABEL)
    )

    top_archive_type_values = enriched["archive_type_display"].value_counts().head(top_archive_types).index.tolist()
    visibility_order = [
        "Evidência pública detectável de audiovisual",
        "Evidência pública indireta de audiovisual",
        "Potencial audiovisual em navegação interna",
        "Sem evidência pública detectável de audiovisual",
        "Site indisponível para verificação",
    ]

    matrix_source = enriched[enriched["archive_type_display"].isin(top_archive_type_values)].copy()
    if matrix_source.empty:
        return pd.DataFrame()

    matrix = pd.crosstab(matrix_source["archive_type_display"], matrix_source["audiovisual_visibility"])
    available_visibility_columns = [col for col in visibility_order if col in matrix.columns]
    matrix = matrix.reindex(
        index=top_archive_type_values,
        columns=available_visibility_columns,
        fill_value=0,
    )
    matrix.index.name = "tipo_institucional"
    return matrix.reset_index()


def build_analysis_exports(summary_df, links_df):
    summary_analysis_df = build_summary_analysis_df(summary_df)
    video_catalog_df = build_video_catalog_df(links_df)
    _, visibility_summary_df = build_visibility_summary(summary_df)
    theme_summary_df = build_theme_summary(video_catalog_df)
    theme_country_df = build_theme_country_summary(video_catalog_df, top_n=None)
    return {
        "summary_analysis": summary_analysis_df,
        "video_catalog": video_catalog_df,
        "visibility_summary": visibility_summary_df,
        "theme_summary": theme_summary_df,
        "theme_country_summary": theme_country_df,
    }


__all__ = [
    "NOISE_THEME_LABEL",
    "build_analysis_exports",
    "build_archive_type_summary",
    "build_availability_reference",
    "build_availability_summary",
    "build_detected_sites_df",
    "build_geography_summaries",
    "build_institution_segments",
    "build_platform_summary",
    "build_summary_analysis_df",
    "build_theme_archive_type_matrix",
    "build_theme_archive_type_summary",
    "build_theme_country_matrix",
    "build_theme_country_summary",
    "build_theme_platform_summary",
    "build_theme_summary",
    "build_video_catalog_df",
    "build_visibility_archive_type_matrix",
    "build_visibility_archive_type_summary",
    "build_visibility_summary",
    "classify_audiovisual_visibility",
    "classify_availability_group",
    "classify_availability_reason",
    "filter_curatorial_video_catalog",
    "format_video_date",
    "infer_video_theme",
    "normalize_optional_text",
    "normalize_text",
]
